engines:
  eslint:
    enabled: true
    channel: 'eslint-3'
    config:
      extensions:
      - .js
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
      - SHIT
      - CRAP
      - ХУЙНЯ
      paths:
      - "README.md"
      - "src/**/*"
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      paths:
      - "src/**/*"
ratings:
   paths:
   - "src/**/*"
   - "**.md"
