engines:
  eslint:
    enabled: true
    channel: 'eslint-3'
    config:
      extensions:
      - .js
ratings:
   paths:
   - "src/**/*"
   - "**.md"
checks:
  method-lines:
    config:
      threshold: 80
  method-complexity:
    config:
      threshold: 16
  complex-logic:
    config:
      threshold: 6
