language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
- '5'
- '4'
install:
- NODE_ENV=development npm install
before_script:
- npm run lint
script:
- npm run test:coverage
after_script:
- npm run test:report
deploy:
  provider: npm
  email: npm@devlato.com
  api_key:
    secure: G+g33PbSygzcZExCnjHitbrxvcSexzoWlrCDbiv6aQhQV4UbEG5yxsvQATchTJz0K5mjXdl6ZPfIVYa5khoEzhUv5f378IMlNxCs7Uz9MQ/SG/2a+pi4pLqg1lOv9nhqvWPiq83mxOucJQqBS4ahtSIUdYT94yxNlGIGGqvuMEEmZ734Sp8IDJt3ASO7ki5CycgvKtI8yqVRwUq4u1jtefb555mx3GkFN4nDG6Va/7F+ZpSykUGLbDkJrD1XdJvOTvzuSFqoMTi1SZgTW4MSoivGvjwy03oLXW+27OZQ9qDU423YsqWMKHOZUqIerHKoYj/dPoOZKc6wBWAXw8uEb2EBcFsMUEt2mFIUV7ndafzys3DclBF4ebft7SJaDi4KipyvQT/mOtO88aU4hJsGF5vLJ9HBVKeJ5ujBT7EfFnygmrBP6a1wIhnG1IVWC5xjSabXFuyGcY3zMuxKqip362fB2vISV8cZBhIPfFu398WhM7Q6SryIhTlvyyNWNZ3lgJdwioZlZWzyT9NV+Qbl2e/3MRfc8I1DWWjXLt5O1sVH0DY7iXGCQL+UR5qVsM8lqQvVr3Lij0vwT4O6S+SVuLDxg8Px5aSg/qZeMRdQTLfjKTQASimhUT7AwmAAa5sppkcqhYfreGQ4B7tOO5oZWUxkV75PtvXECCz5XWFX+yA=
  on:
    tags: true
    repo: devlato/waitUntil
