language: node_js
node_js:
- '14'
- '13'
- '12'
- '11'
- '10'
install:
- NODE_ENV=development npm install
before_script:
- npm run lint
script:
- npm run test:coverage
after_script:
- npm run test:report
deploy:
  provider: npm
  email: npm@devlato.com
  api_key:
    secure: KtCcXMm9URGfxEa83WTTNOBuwKXrDp6NDYQCJEkwFk0PJtuFguCe9XW+RQOIWvticUArCj07fklr8cleFzjwDfatH+WiZ4upGZZbpOfoEKyeBsv2XhIAxgPxB0OY/BZFCTbzXVNM6BFzMWiHN0/PYmlMa8AuE2tOCjuenOntEFBbMSXARVjm9rUYoPH3IVyPiaqadWChREHNXkYlsHvDxHsB4rxDaQGSu9YtdbIWU3T2W16bKNIi566SklBjrfAldV3p4sdhbg+QxMBB6/fO5pn/L322IUEBBcrLTx3e9PDMgRuGFkWmCMQi/Wktm259OxHWVD+L7eUK9qr3WAbSKt8ag/30ue0FbAFGSJjLpLUnSTacehezY91MND8AzC4O8b2F8VNXryV6Ei/zyYzWpqLC/TmfFnyNys+ih0nc5T8UOVbcSOyI3Ur7pbPFyWr3ZsF3YNc/xlnFaXYY2IqQdoHExMUsfSjPKf3aS7qBsQd9p/IyOSG0LEYahPxvNblZlThMm7IUUEaITvdZUm2zzN9ma13qIbwuQ4EKKSJWhk/v2CXxmA8Rf86a6H0PS2GoS1IHnolDr8PdFLB+PcJS7dhun1663RmZ08lAJ//7mXn4KojgBkgILBTQBtXDCwq+q3Z/9wy6UWIia1jcx3vm0MTcGtc8zDnXuFAwAw0Y8Lc=
  on:
    tags: true
    repo: devlato/async-wait-until
